version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # Cambia esto por una contraseña segura
      MYSQL_DATABASE: bdtestsqlalchemy
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py  # Cambia esto si tu archivo principal tiene otro nombre
    depends_on:
      - db

volumes:
  mysql_data:
